#!/usr/bin/env bash
set -e

echo 'Creating output directory'
output="$(./libexec/make_output_directory.sh)"

echo 'Reformatting sentences'
filename="$1" ./libexec/untab_sentences.sh > "$output/untabbed.txt"

echo 'Running through OpenIE'
input="$output/untabbed.txt" output="$output/openie_output.txt" ./libexec/get_openie_output.sh

echo 'Parsing OpenIE output to get permutations'
./libexec/parse_openie.py "$output"

echo 'Running permutations through Semafor'
output="$output" ./libexec/get_semafor_output.sh
