#!/usr/bin/env bash
set -e

echo 'Creating output directory'
output="$(./libexec/make_output_directory.sh)"

echo 'Reformatting sentences'
filename="$1" ./libexec/untab_sentences.sh > "$output/untabbed.txt"

echo 'Running through OpenIE'
input_file="$output/untabbed.txt" ./libexec/get_openie_output.sh > "$output/openie_output.txt"

echo 'Parsing OpenIE output'
./libexec/parse_openie.py "$output"

echo 'Cleaning up'
./libexec/unset_globals.sh
