OUTPUT_DIRECTORY='output'
OPENIE_DIRECTORY='/local/tools/openie-master'
SEMAFOR_RELEASE_DIRECTORY='/home/evan/Coding/study/indep/TextSimilarity/evan/semafor/release'
WORD2VEC_DIRECTORY='/home/evan/Coding/study/indep/TextSimilarity/evan/word2vec'
WORD2VEC_MODEL='/local/models/word2vec-models/GoogleNews-vectors-negative300.bin'
